### ISSUE TITLE
to_praat() issue

### ISSUE THREAD

**Issue by ziweizh** [scjs/tgre#1]
When I tried to extract the tier from TextGrid and write to file, there was an attribute error:
`
import tgre
tg = tgre.TextGrid.from_file('/Users/ziweizh/Documents/ISU_ALT/2017_Spring/ENGL_515/Final_Project/RSMTool/Feature_Extraction/Prosody/MFA_output/001_1.TextGrid') 
tg_word_tier = tgre.TextGrid(tg.tiers[0].xmin, tg.tiers[0].xmax, tiers = tg.tiers[0])
tg_word_tier.to_praat(path='001_1.TextGrid')
`

Here is the error I got:
AttributeError: 'Interval' object has no attribute 'name'

**Comment by scjs** [comment]
When you're creating a new TextGrid, the `tiers` argument needs to be a list of tiers - right now it's just being passed a single tier object. Try this:

    tg_word_tier = tgre.TextGrid(tg.tiers[0].xmin, tg.tiers[0].xmax, tiers=[tg.tiers[0]])

**Comment by ziweizh** [comment]
Thanks. It worked :)

**Comment by scjs** [comment]
Great!
